name: Python CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest  # Use Windows-based runner for CI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Specify the Python version you want

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Run tests using pytest

    - name: Build Docker image (optional)
      run: |
        docker build -t my-python-app .

    - name: Deploy to Staging
      run: |
        echo "Deploying to staging..."

  deploy-production:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
